"""
weather_to_epw simulator tool.
"""

from .common import *  # noqa: F401,F403

def weather_to_epw(
    weather_timeseries_path: str,
    *,
    run_id: str = "run-weather-epw",
    instance_id: str = "instance-001",
    scenario_name: str = "baseline",
    scenario_description: str = "",
    assumptions: dict[str, Any] | None = None,
    seed: int = 11,
    model_version: str = "oracle:weather_to_epw@1.0.0",
    container_image: str | None = None,
    threads: int = 1,
    cpu_cores: int = 1,
    memory_gb: float = 1.0,
    timeout_seconds: int = 120,
    city: str = "SyntheticCity",
    country: str = "USA",
    latitude: float = 0.0,
    longitude: float = 0.0,
    timezone: float = 0.0,
    elevation_m: float = 100.0,
    output_path: str = "./data/simulators/weather.epw",
) -> ToolResponse:
    """
    Convert daily or hourly weather CSV into an EPW-style file for EnergyPlus proxies.

    Supported input columns:
    - date or timestamp
    - tair_c (or tmean_c / tmax_c+tmin_c)
    - rh_pct (optional)
    - wind_m_s (optional)
    """

    tool_name = "weather_to_epw"
    start_ts = time.perf_counter()
    run_context = _build_run_context(
        run_id=run_id,
        instance_id=instance_id,
        scenario_name=scenario_name,
        scenario_description=scenario_description,
        start_iso=None,
        end_iso=None,
        timestep="hourly",
        assumptions=assumptions,
        seed=seed,
        model_version=model_version,
        container_image=container_image,
        threads=threads,
        cpu_cores=cpu_cores,
        memory_gb=memory_gb,
        timeout_seconds=timeout_seconds,
        inputs=[(weather_timeseries_path, "weather forcing for EPW conversion")],
    )
    warnings: list[str] = []
    try:
        rows = _load_rows(weather_timeseries_path)
        if not rows:
            return _error(tool_name, "Weather timeseries input is empty.", start_ts=start_ts, run_context=run_context)
        rng = random.Random(seed)

        hourly_rows: list[dict[str, Any]] = []
        for row in rows:
            timestamp = _parse_datetime_from_row(row)
            if timestamp is None:
                continue
            if any(key in row for key in ("hour", "Hour")):
                temp = _as_float(
                    row.get("tair_c"),
                    _as_float(row.get("tmean_c"), (_as_float(row.get("tmin_c")) + _as_float(row.get("tmax_c"))) / 2.0),
                )
                rh = _clamp(_as_float(row.get("rh_pct"), 55.0), 1.0, 100.0)
                wind = max(0.0, _as_float(row.get("wind_m_s"), 1.5))
                hourly_rows.append({"timestamp": timestamp, "temp": temp, "rh": rh, "wind": wind})
                continue

            tmin = _as_float(row.get("tmin_c"), _as_float(row.get("tair_c"), 18.0) - 3.0)
            tmax = _as_float(row.get("tmax_c"), _as_float(row.get("tair_c"), 18.0) + 3.0)
            rh_daily = _clamp(_as_float(row.get("rh_pct"), 58.0), 1.0, 100.0)
            wind_daily = max(0.0, _as_float(row.get("wind_m_s"), 1.8))
            for hour in range(24):
                phase = ((hour - 7) / 24.0) * 2.0 * math.pi
                temp = (tmin + tmax) / 2.0 + (tmax - tmin) / 2.0 * math.sin(phase)
                temp += rng.uniform(-0.25, 0.25)
                rh = _clamp(rh_daily + rng.uniform(-5.0, 5.0), 1.0, 100.0)
                wind = max(0.0, wind_daily + rng.uniform(-0.5, 0.5))
                hourly_rows.append({"timestamp": timestamp + timedelta(hours=hour), "temp": temp, "rh": rh, "wind": wind})

        if not hourly_rows:
            return _error(tool_name, "Unable to derive hourly rows from weather input.", start_ts=start_ts, run_context=run_context)

        hourly_rows.sort(key=lambda row: row["timestamp"])
        run_dir = _tool_run_dir(DEFAULT_OUTPUT_DIR, tool_name, run_id, scenario_name)
        epw_path = _resolve_output_path(output_path, fallback_dir=run_dir, filename="weather.epw")

        header_lines = [
            f"LOCATION,{city},-,{country},SyntheticTMY,000000,{latitude:.4f},{longitude:.4f},{timezone:.1f},{elevation_m:.1f}",
            "DESIGN CONDITIONS,0",
            "TYPICAL/EXTREME PERIODS,0",
            "GROUND TEMPERATURES,0",
            "HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0",
            "COMMENTS 1,Generated by weather_to_epw deterministic oracle tool",
            "COMMENTS 2,For agentic simulation workflows",
            "DATA PERIODS,1,1,Data,Sunday,1/1,12/31",
        ]

        with epw_path.open("w", encoding="utf-8") as handle:
            handle.write("\n".join(header_lines) + "\n")
            for row in hourly_rows:
                ts = row["timestamp"]
                dry_bulb = row["temp"]
                dew_point = dry_bulb - (100.0 - row["rh"]) / 6.0
                pressure = 101325
                wind_dir = int((ts.timetuple().tm_yday * 17 + ts.hour * 13 + seed * 7) % 360)
                wind_speed = row["wind"]
                fields = [
                    ts.year,
                    ts.month,
                    ts.day,
                    ts.hour + 1,
                    60,
                    "A7A7A7A7",
                    f"{dry_bulb:.2f}",
                    f"{dew_point:.2f}",
                    f"{row['rh']:.1f}",
                    pressure,
                    9999,
                    9999,
                    9999,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    wind_dir,
                    f"{wind_speed:.2f}",
                    5,
                    4,
                    25,
                    77777,
                    9,
                    999999999,
                    2.5,
                    0.1,
                    0,
                    88,
                    0.2,
                    0,
                    0,
                ]
                handle.write(",".join(str(item) for item in fields) + "\n")

        summary_path = run_dir / "epw_conversion_summary.json"
        _write_json(
            summary_path,
            {
                "hourly_rows": len(hourly_rows),
                "start": hourly_rows[0]["timestamp"].isoformat(),
                "end": hourly_rows[-1]["timestamp"].isoformat(),
                "seed": seed,
            },
        )
        outputs = [
            _artifact_record(epw_path, "EPW weather file for EnergyPlus-like simulations"),
            _artifact_record(summary_path, "EPW generation metadata"),
        ]
        mean_temp = statistics.fmean(row["temp"] for row in hourly_rows)
        metrics = {
            "hourly_records": _metric(float(len(hourly_rows)), "count"),
            "dry_bulb_mean_c": _metric(mean_temp, "degC"),
        }
        derived = {
            "dry_bulb_p95_c": _metric(_percentile([row["temp"] for row in hourly_rows], 0.95), "degC"),
        }
        agentic_summary = {
            "headline": f"Created EPW forcing with {len(hourly_rows)} hourly records for {scenario_name}.",
            "primary_signal": {"metric": "dry_bulb_mean_c", **metrics["dry_bulb_mean_c"]},
            "risk_level": "none",
            "comparison_ready": True,
            "recommended_next_tools": ["impact_energyplus_run"],
        }
        return _success(
            tool_name=tool_name,
            start_ts=start_ts,
            metrics=metrics,
            derived_metrics=derived,
            output_artifacts=outputs,
            run_context=run_context,
            warnings=warnings,
            agentic_summary=agentic_summary,
        )
    except Exception as exc:
        return _error(tool_name, str(exc), start_ts=start_ts, run_context=run_context, warnings=warnings)


__all__ = ["weather_to_epw"]
